### ISSUE TITLE
Current Sensor Readings

### ISSUE THREAD

**Issue by gabesoares** [sfuphantom/vcu-fw#1]
Implement analog readings for current sensor. This sensor measures the high current path between battery and inverter. This will be able to measure both positive and negative currents. Negative will correspond to regenerative braking. 

- [ ] Include max positive current level and min negative current level as defines in the board_hardware.h file for both launchpad and VCU. 

- [ ] Write out a function that can convert the current sensor 0->5V analog signal into a current. You will need to use the current sensor datasheet to get the proper mapping function. 

- [ ] Write out some error checking and a function that throws a fault if the current reading is not in the proper bounds. 

- [ ] Package the functions into a driver (current_transducer.h/current_transducer.c) and put it in its own folder similar to where the DAC_SPI driver folder is

- [ ] Implement the function calls from the driver in the VCU's sensor_read task

**Comment by gabesoares** [comment]
Datasheet: https://www.lem.com/sites/default/files/products_datasheets/htfs_200_800-p.pdf

**Comment by rafguevara14** [comment]
this sensor is also on the BMS
