### ISSUE TITLE
APPS Implausibility

### ISSUE THREAD

**Issue by jaypacamarra** [sfuphantom/vcu-fw#14]
According to rule from 2022 Formula SAE official rules,
T.4.2.5 If an implausibility occurs between the values of the APPSs and persists for more than 100msec, the power to the (IC) electronic throttle / (EV) Motor(s) must be immediately stopped completely.
(EV only) It is not necessary to Open the Shutdown Circuit, the motor controller(s) stopping the power to the Motor(s) is sufficient.

**Objective**
Change the necessary code in the throttle task such that when an APPS implausibility (APPS1 & APPS2 differs by more than 10%) occurs, we ignore all consequent throttle commands, or set THROTTLE_AVAILABLE to false. Double-check this solution with the controls team.

**Comment by jaypacamarra** [comment]
Hint: You'll need to modify the logic for setting the throttle in task_throttle.c
![image](https://user-images.githubusercontent.com/32022111/143172630-aca19986-ae37-466b-a0f5-c86fe60b5820.png)

**Comment by rafguevara14** [comment]
This should be fixed already. We should run a quick test to validate this

**Comment by rafguevara14** [comment]
stale issue

**Comment by rafguevara14** [comment]
firmware handles this already. see where suspend throttle is called
