### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by jaypacamarra** [sfuphantom/vcu-fw#16]
Can we can delete these?
![image](https://user-images.githubusercontent.com/32022111/150916330-0b4375fe-37f8-4ee2-b5d2-4811da3ffa91.png)

Can we include some of these into the .gitignore?
![image](https://user-images.githubusercontent.com/32022111/150916492-ae0746b2-0490-4e38-9fe4-c63779142b44.png)

Why are there two .gitignores?
![image](https://user-images.githubusercontent.com/32022111/150916549-225e67dd-dd5e-464a-80be-f0d6255c1674.png)
![image](https://user-images.githubusercontent.com/32022111/150916570-87504a26-345a-40f2-af57-e5219ee42d0e.png)

**Comment by Guojiaxi** [comment]
I pushed a change just now to the gitignores to exclude the directories you mentioned. However, those excluded folders may still be in the repo and will need to be manually deleted from it.

Also, I also excluded the BuildConfig_* folders. Maybe this will stop the "f021.h" error.

The changes were pushed to 2022-refactor btw.

**Comment by rafguevara14** [comment]
stale issue
