### ISSUE TITLE
2B: Handle the RTD procedure

### ISSUE THREAD

**Issue by kkramer215** [sfuphantom/vcu-fw#27]
This function will handle the ready to drive (RTD) procedure as per the rule book requirements. When the driver flips a switch the function will check if the brake is pressed and if the tractive system is active. If both the brake is pressed and the tractive system is active the function will enable the motors to respond to inputs from the throttle. 
The brake being pressed is determined by checking if the sensor value is above a specific threshold. If the tractive system is active is determined by checking the status of the TSAL function (previously written function).

**Comment by rafguevara14** [comment]
The handling of the events in the RTD procedure was completed [here](https://github.com/sfuphantom/vcu-fw/commit/0e4ab76bc5661b6b59394b02642f0ff35eff44d4). Now the events have to be detected via hardware interrupts.

**Comment by rafguevara14** [comment]
Closing and creating a new issue for the hardware part
