### ISSUE TITLE
4A: Command Line Interface for passing throttle values

### ISSUE THREAD

**Issue by kkramer215** [sfuphantom/vcu-fw#31]
Before testing real throttle petal values (APPS1, APPS2, BSE), we must ensure that the VCU code accurately processes input values. This script will be a Python command line interface for passing values from your local CMD/Terminal to the microcontroller:

This interface is tailored towards the refactor in this branch:

https://github.com/sfuphantom/vcu-fw/blob/Throttle-refactor/VCU/Phantom/Drivers/THROTTLE/README.md

**Comment by kevinl03** [comment]
The script was used to send one set of values [APPS1, APPS2, BSE] at a time so that we can easily check that the VCU was receiving he values.

**Comment by kevinl03** [comment]
Implementation found here: 

https://github.com/sfuphantom/vcu-fw/blob/Throttle_Simulator_Script/command-line/Throttle_Value_Simulator.py
