### ISSUE TITLE
Fix Throttle Fault Timers 

### ISSUE THREAD

**Issue by rafguevara14** [sfuphantom/vcu-fw#37]
We need to figure out when these are triggered so that we can avoid them when developing and testing other features. It's also possible that these don't really work as expected...

https://github.com/sfuphantom/vcu-fw/blob/a6cba0043ec8ddae5682d43976287c164753363d/VCU/Phantom/tasks/source/task_throttle_actor.c#L110

**Comment by kkramer215** [comment]
Best to figure this out ASAP to avoid trying to "fix" other code that might be impacted by the timers. Would be good to try to isolate the timers to see if working properly or not.

**Comment by rafguevara14** [comment]
Looks like this gets fixed by the new architectural design. will link PR once it's up!
Specifically, watch out for the `NotifyStateMachineFromTimer` in these changes

https://github.com/sfuphantom/vcu-fw/blob/Finalize-VCU-Infrastructure/Diagrams/Threads/threads.svg

**Comment by rafguevara14** [comment]
PR is merged
