### ISSUE TITLE
Move to tractive off state when high voltage is off

### ISSUE THREAD

**Issue by rafguevara14** [sfuphantom/vcu-fw#43]
https://viewer.diagrams.net/?page-id=BhlIVNj5Ru_8s9wX0_BA&highlight=0000ff&edit=_blank&layers=1&nav=1&hide-pages=1#G1uKblakAovlpPvJciPE8IRBLEZo3NYH4g

The BMS will be sending a TSAL bit over CAN to the VCU. The job of sending that information is left to the CAN team.

Create a new event in eCarEvents and implement the necessary logic in the VCU state machine according to the diagram linked above.

Prerequisites:
TSAL -> Tractive System Active Light 

Refer to here: https://docs.google.com/document/d/1Ut_q42FNuqnMAqmwgvhiAlQ1F1jr7UJEptP9l4vzhDA/edit

eCarEvents: the events of the state machine

Relevant VCU files:

vcu_common.h has eCarEvents
state_machine.c has the state machine

Not relevant for now:
You may add to the [command list](https://github.com/sfuphantom/vcu-fw/blob/75cedb33bb1e8c02da3b148fc5e2a9a2065334d3/VCU/Phantom/Drivers/UART/Phantom_sci.c#L23) to inject the event for testing

**Comment by juliannesoriano20** [comment]
Should VCU_FLT be kept high until the car is reset? I think it is good to keep VCU_FLT high whenever we have a fault, that way SDB is sure to act upon the signal. Then, only turn low once the car is reset and then we can set VCU_FLT low
